package com.airbandme.app.responseModels.signup

data class User(
    val always_open: String,
    val apple_id: String,
    val bio: String,
    val business_address: String,
    val business_brief: String,
    val business_name: String,
    val business_products_services: String,
    val category_id: Any,
    val city: String,
    val contact_number: String,
    val country: String,
    val country_code: String,
    val device_id: String,
    val device_type: String,
    val email: String,
    val facebook_id: String,
    val first_name: String,
    val gender: String,
    val google_id: String,
    val id: Int,
    val join_world_list: String,
    val last_name: String,
    val p_o_box: String,
    val phone: String,
    val profile_image: String,
    val state: String,
    val token: String,
    val username: String,
    val website_link: String,
    val type: String,

)